// Generated by CoffeeScript 1.4.0
(function() {
  var intersect;

  intersect = function(arr1, arr2) {
    var i, l, o, r, v;
    r = [];
    o = {};
    l = arr2.length;
    i = void 0;
    v = void 0;
    i = 0;
    while (i < l) {
      o[arr2[i]] = true;
      i++;
    }
    l = arr1.length;
    i = 0;
    while (i < l) {
      v = arr1[i];
      if (v in o) {
        r.push(v);
      }
      i++;
    }
    return r;
  };

  $(function() {
    var x, y;
    x = "";
    y = "";
    if (categorizr.isDesktop) {
      $("a.collection").each(function() {
        x = $(window).width();
        x = x / 5;
        y = (x * (498 / 400)) / 2;
        return $(this).width(x).height(y);
      });
      $(".collections").height(y);
      $(window).resize(function() {
        $("a.collection").each(function() {
          x = $(window).width();
          x = x / 5;
          y = (x * (498 / 400)) / 2;
          return $(this).width(x).height(y);
        });
        return $(".collections").height(y);
      });
    } else {
      $('a.collection').css({
        'height': '146.91px',
        'width': '236px'
      });
      $('.collections').css({
        'height': '147px'
      });
    }
    $("i[class^=\"icon-chevron-\"]").hover((function() {
      return $(this).css("cursor", "pointer");
    }), function() {
      return $(this).css("cursor", "auto");
    });
    $(".f-one").show();
    $("div[class^=\"f-\"] i[class^=\"icon-chevron-\"]").click(function() {
      var current_slide, i, list, pos;
      list = [];
      $('div.featured div[class^="f-"]').each(function() {
        x = $(this).attr('class').split('f-');
        return list.push(x[1]);
      });
      current_slide = $(this).parents("div[class^=\"f-\"]").attr("class").split("f-");
      pos = intersect(current_slide, list).toString();
      if ($(this).hasClass("icon-chevron-left")) {
        if (i = $.inArray(pos, list) === 0) {
          $(".f-" + pos).fadeOut(250);
          return $(".f-" + list[list.length - 1]).delay(255).fadeIn(250);
        } else {
          $(".f-" + pos).fadeOut(250);
          return $(".f-" + list[$.inArray(pos, list) - 1]).delay(255).fadeIn(250);
        }
      } else {
        if ($.inArray(pos, list) === list.length - 1) {
          $(".f-" + pos).fadeOut(250);
          return $(".f-" + list[0]).delay(255).fadeIn(250);
        } else {
          $(".f-" + pos).fadeOut(250);
          return $(".f-" + list[$.inArray(pos, list) + 1]).delay(255).fadeIn(250);
        }
      }
    });
    $('a.hero_dropdown').click(function() {
      $('div.container.hero').toggleClass('active');
      return $('div.container.hero div.row.hidden').removeClass('hidden');
    });
    $('a.white').click(function() {
      var browse_url, url_array;
      $('div.container.hero').toggleClass('active');
      $('div.container.hero div.row:last').addClass('hidden');
      $('a.hero_dropdown > span').text($(this).text());
      url_array = $('div.hero a.button').attr('href').split("/browse");
      browse_url = url_array[0] + '/browse/' + '?events=' + $(this).data('value');
      return window.location.href = browse_url;
    });
    return $('a.close').click(function() {
      $('div.container.hero').toggleClass('active');
      return $('div.container.hero div.row:last').addClass('hidden');
    });
  });

}).call(this);
