// Generated by CoffeeScript 1.4.0
(function() {
  var clicked;

  $('div.venue').live('hover', function() {
    return $(this).toggleClass('hover');
  });

  if (window.location.href.indexOf('preview') !== -1) {
    $('a.link-to-space').each(function() {
      var url;
      url = $(this).attr('href') + '?preview=true';
      return $(this).attr('href', url);
    });
  }

  $("#accordion").accordion({
    icons: null,
    activate: function(event, ui) {
      $('.venue-images.active > div.pano').empty();
      $('.venue-images.active > div.images').show();
      $('.venue-images.active > div.pano').hide();
      $('.venue-images.active').removeClass('active');
      $($('.venue-images')[$('#accordion').accordion("option", "active")]).addClass('active');
      return $('input#input-space-id').val($('div.venue-images.active > input#space-id').val());
    },
    create: function(event, ui) {
      $('.ui-accordion .ui-accordion-content').css({
        height: "auto"
      });
      $($('.venue-images')[$('#accordion').accordion("option", "active")]).addClass('active');
      return $('input#input-space-id').val($('div.venue-images.active > input#space-id').val());
    }
  });

  $('a.claim').click(function() {
    mixpanel.track("Claim Form - Opened");
    $('.fade').toggle().css('height', document.documentElement.offsetHeight);
    $('.claim-form').show().css({
      'position': 'absolute',
      'top': (window.innerHeight / 2) - 300 + $(document).scrollTop()
    });
    if ($.browser.msie && parseInt($.browser.version) < 9) {
      return window.scrollTo(0, 0);
    }
  });

  $('div.claim-form a.close').click(function() {
    $('.fade').hide();
    $('.claim-form').hide();
    $('div.claim-form div.show-success').hide();
    return $('div.claim-form div.show-form').show();
  });

  $(window).resize(function() {
    if ($('.claim-form').css('display') !== 'none') {
      return $('.claim-form').css({
        'top': (window.innerHeight / 2) - 300,
        'left': (window.innerWidth / 2) - 200
      });
    }
  });

  $(document).scroll(function() {
    if ($('.claim-form').css('display') !== 'none') {
      return $('.claim-form').css({
        'top': (window.innerHeight / 2) - 300 + $(document).scrollTop()
      });
    }
  });

  clicked = false;

  $('div.claim-form input#btn-submit-claim-form').click(function(e) {
    if (!clicked) {
      clicked = true;
      $("input#btn-submit-claim-form").val("Sending...");
      e.preventDefault();
      if ($("input#input-claim-email").val() !== "") {
        return $.post(domain + 'api/add_b2b', {
          email: $("input#input-claim-email").val(),
          name: $("input#input-claim-name").val(),
          venue: $("input#input-claim-venue-name").val(),
          phone: $("input#input-claim-phone").val(),
          state: $("input#input-claim-state").val(),
          source: 'claim-your-venue',
          comments: $("textarea#input-claim-comments").val(),
          referrer: null,
          success_msg: 'Thank you for claiming your venue - we\'ll be in touch soon!'
        }, function(data) {
          clicked = false;
          $("input#btn-submit-claim-form").val("Submit");
          if (data.success) {
            mixpanel.track("Claim Form - Submission Successful");
            return flashalert('success', data.result, 'inline', $("input#btn-submit-claim-form"), 20);
          } else {
            mixpanel.track("Claim Form - Submission Failure");
            return flashalert('error', data.result, 'inline', $("input#btn-submit-claim-form"), 20);
          }
        }, 'json');
      } else {
        $("input#btn-submit-claim-form").val("Submit");
        return flashalert('error', "Please enter an email address", 'inline', $("input#btn-submit-claim-form"), 20);
      }
    }
  });

}).call(this);
